apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweet-db
  namespace: mimir
  labels:
    app: tweet-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweet-db
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          ports:
            - name: tweet-db-port
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: database
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tweet-db-volume
          livenessProbe:
            exec:
              command: ["pg_isready", "-h", "localhost", "-U", "postgres"]
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-h", "localhost", "-U", "postgres"]
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: tweet-db-volume
          persistentVolumeClaim:
            claimName: tweet-db-vol-claim
