apiVersion: v1
kind: PersistentVolume
metadata:
  name: news-db-vol
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 120Mi
  hostPath:
    path: /data/news-db-vol/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-db-vol-claim
  namespace: mimir
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Mi
