DROP TABLE IF EXISTS LATEST_PRICE;

CREATE TABLE LATEST_PRICE (
  TICKER VARCHAR(20) PRIMARY KEY,
  DATE_INSERTED TIMESTAMP,
  PRICE NUMERIC(15,4),
  PRICE_CHANGE NUMERIC(7,4),
  CURRENCY VARCHAR(10)
);

DROP TABLE IF EXISTS CLOSE_PRICE;

-- Changed from HISTORICAL_PRICE
CREATE TABLE CLOSE_PRICE (
  TICKER VARCHAR(20) REFERENCES LASTEST_PRICE(TICKER),
  PRICE_DATE DATE,
  PRICE NUMERIC(15,4),
  CURRENCY VARCHAR(10),
  PRIMARY KEY (TICKER, PRICE_DATE)
);


DROP TABLE IF EXISTS HISTORICAL_PRICE;

CREATE TABLE HISTORICAL_PRICE (
  TICKER VARCHAR(20) REFERENCES LATEST_PRICE(TICKER),
  PRICE NUMERIC(15,4),
  CURRENCY VARCHAR(10),
  DATE_INSERTED TIMESTAMP,
  PRIMARY KEY (TICKER, DATE_INSERTED)
);
