DROP TABLE IF EXISTS HISTORICAL_PRICE;

CREATE TABLE HISTORICAL_PRICE (
  TICKER VARCHAR(20),
  PRICE_DATE DATE,
  PRICE NUMERIC(15,4),
  PRIMARY KEY (TICKER, PRICE_DATE)
);


DROP TABLE IF EXISTS STOCK_PRICE;

CREATE TABLE STOCK_PRICE (
  TICKER VARCHAR(20) PRIMARY KEY,
  PRICE NUMERIC(15,4),
  DATE_INSERTED TIMESTAMP
);
