kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs-standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: true
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-central-1a
