DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  ID VARCHAR(64) PRIMARY KEY,
  EMAIL VARCHAR(100),
  JOIN_DATE DATE,
);

DROP TABLE IF EXISTS SESSION;
CREATE TABLE SESSION (
  USER VARCHAR(64) REFERENCES USER(ID),
  SESSION_START TIMESTAMP
);

DROP TABLE IF EXISTS SERACH_HISTORY;
CREATE TABLE SEARCH_HISTORY (
  USER VARCHAR(64) REFERENCES USER(ID),
  SEARCH_TERM VARCHAR(100),
  DATE_INSERTED TIMESTAMP
);

DROP TABLE IF EXISTS USER_TICKERS;
CREATE TABLE USER_TICKERS (
  USER VARCHAR(64) REFERENCES USER(ID),
  NAME VARCHAR(20) REFERENCES STOCK(TICKER),
  FOLLOWING BOOLEAN,
  PRIMARY KEY (USER, NAME)
);

DROP TABLE IF EXISTS STOCK;
CREATE TABLE STOCK (
  TICKER VARCHAR(20) PRIMARY KEY,
  NAME VARCHAR(100),
  DESCRIPTION TEXT,
  IMAGE_URL VARCHAR(200),
  WEBSITE VARCHAR(200),
  MINUTE INTEGER
);

DROP TABLE IF EXIST STOCK_VOLUME;
CREATE TABLE STOCK_VOLUME (
  TICKER VARCHAR(20) REFERENCES STOCK(TICKER),
  0 INTEGER,
  1 INTEGER,
  2 INTEGER,
  4 INTEGER,
  5 INTEGER,
  6 INTEGER,
  7 INTEGER,
  8 INTEGER,
  9 INTEGER,
  10 INTEGER,
  11 INTEGER,
  12 INTEGER,
  13 INTEGER,
  14 INTEGER,
  15 INTEGER,
  16 INTEGER,
  17 INTEGER,
  18 INTEGER,
  19 INTEGER,
  20 INTEGER,
  21 INTEGER,
  22 INTEGER,
  23 INTEGER
)
