apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-api
  namespace: mimir
  labels:
    app: admin-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/admin-api:latest
          ports:
            - name: api-port
              containerPort: 8000
          env:
            - name: TOKEN_EXPIRIY_MINUTES
              value: "60"
            - name: ADMIN_API_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-api-credentials
                  key: accessKey
            - name: ADMIN_API_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: admin-api
            - name: TWEET_DB_HOST
              value: tweet-db
            - name: TWEET_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: tweet-db
            - name: TWEET_DB_USER
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: username
            - name: TWEET_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: password
            - name: TWEET_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: database
            - name: APP_DB_HOST
              value: app-db
            - name: APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: app-db
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: username
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: password
            - name: APP_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: database
