apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
  namespace: mimir
  labels:
    app: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/webserver:latest
          ports:
            - name: webserver-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: webserver-port
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: webserver-port
            initialDelaySeconds: 30
