apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-db-vol
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 120Mi
  hostPath:
    path: /data/app-db-vol/
