apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stats-calc
  namespace: mimir
  labels:
    app: stats-calc
spec:
  schedule: "5 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: stats-calc
              image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/stats-calc:latest
              env:
                - name: TWEET_DB_HOST
                  value: tweet-db
                - name: TWEET_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: tweet-db-credentials
                      key: password
                - name: TWEET_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: tweet-db-credentials
                      key: username
                - name: TWEET_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: tweet-db-credentials
                      key: database
                - name: TWEET_DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: service-ports
                      key: tweet-db
                - name: APP_DB_HOST
                  value: app-db
                - name: APP_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: app-db-credentials
                      key: password
                - name: APP_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: app-db-credentials
                      key: username
                - name: APP_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: app-db-credentials
                      key: database
                - name: APP_DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: service-ports
                      key: app-db
                - name: STABLE_DATE
                  value: "2018-01-20"
