-- ARTICLE TABLES
DROP TABLE IF EXISTS COMPOUND_SCORE;
DROP TABLE IF EXISTS SUBJECT_SCORE;
DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE ARTICLE (
  URL_HASH VARCHAR(64) PRIMARY KEY,
  URL VARCHAR(350) NOT NULL,
  TITLE VARCHAR(350) NOT NULL,
  REFERENCE_SCORE NUMERIC(9,5) NOT NULL,
  SUMMARY TEXT,
  BODY TEXT,
  DATE_INSERTED TIMESTAMP,
  TWITTER_REFERENCES BIGINT[],
  KEYWORDS VARCHAR(50)[]
);

CREATE TABLE COMPOUND_SCORE (
  URL_HASH VARCHAR(64) REFERENCES ARTICLE(URL_HASH),
  TICKER VARCHAR(15),
  SCORE NUMERIC(9,5) NOT NULL,
  PRIMARY KEY (URL_HASH, TICKER)
);

CREATE TABLE SUBJECT_SCORE (
  URL_HASH VARCHAR(64) REFERENCES ARTICLE(URL_HASH),
  TICKER VARCHAR(15),
  SCORE NUMERIC(9,5),
  PRIMARY KEY (URL_HASH, TICKER)
);

-- CLUSTER TABLES
DROP TABLE IF EXISTS CLUSTER_MEMBER;
DROP TABLE IF EXISTS ARTICLE_CLUSTER;

CREATE TABLE ARTICLE_CLUSTER (
  CLUSTER_HASH VARCHAR(64) PRIMARY KEY,
  TITLE VARCHAR(255),
  TICKER VARCHAR(15),
  ARTICLE_DATE DATE,
  LEADER VARCHAR(64), -- URL_HASH of the cluter leader
  SCORE NUMERIC(9,5)
);

CREATE TABLE CLUSTER_MEMBER (
  CLUSTER_HASH VARCHAR(64) REFERENCES ARTICLE_CLUSTER(CLUSTER_HASH),
  URL_HASH VARCHAR(64),
  REFERENCE_SCORE NUMERIC(9,5),
  SUBJECT_SCORE NUMERIC(9,5),
  PRIMARY KEY(CLUSTER_HASH, URL_HASH)
);
