apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-server
  namespace: mimir
  labels:
    app: search-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: search-server
    spec:
      containers:
        - name: search-server
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/search-server:latest
          ports:
            - name: ss-port
              containerPort: 7000
          env:
            - name: PG_HOST
              value: tweet-db
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: database
