DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
  ID VARCHAR(64) PRIMARY KEY,
  EMAIL VARCHAR(100),
  TICKERS VARCHAR(64)[],
  JOIN_DATE DATE
);


DROP TABLE IF EXISTS SESSION;

CREATE TABLE SESSION (
  USER_ID VARCHAR(64) REFERENCES APP_USER(ID),
  SESSION_START TIMESTAMP
);


DROP TABLE IF EXISTS SERACH_HISTORY;

CREATE TABLE SEARCH_HISTORY (
  USER_ID VARCHAR(64) REFERENCES APP_USER(ID),
  SEARCH_TERM VARCHAR(100),
  DATE_INSERTED TIMESTAMP
);


DROP TABLE IF EXISTS STOCK;

CREATE TABLE STOCK (
  TICKER VARCHAR(20) PRIMARY KEY,
  NAME VARCHAR(100),
  DESCRIPTION TEXT,
  IMAGE_URL VARCHAR(200),
  WEBSITE VARCHAR(200)
);


DROP TABLE IF EXISTS TWITTER_DATA;

CREATE TABLE TWITTER_DATA (
  TICKER VARCHAR(64) PRIMARY KEY REFERENCES STOCK(TICKER),
  MINUTE INTEGER,
  VOLUME INTEGER[],
  BUSDAY_MEAN NUMERIC(12,2)[],
  WEEKEND_MEAN NUMERIC(12,2)[],
  BUSDAY_STDEV NUMERIC(12,2)[],
  WEEKEND_STDEV NUMERIC(12,2)[]
);
