INSERT INTO training_data (text, label, created_at) VALUES
('RT @ElixiumCapital: Trade with #Bitcoin', 'SPAM', NOW()),
('RT @ElixiumCapital: Trade with', 'SPAM', NOW()),
('RT @BIGMONEYMIKE6: WHEN MY NAME ( #BMM ) COMES UP , RESPEK IT !!!!', 'SPAM', NOW()),
('RT @BIGMONEYMIKE6: THINGS OF UTMOST IMPORTANCE 1) GOD 2) FAMILY 3) SELF 4) #PENNYSTOCKS 5) WIFEY', 'SPAM', NOW()),
('RT @BColwell_Invest: #Nvidia DCF Implied Valuation - $nvda #tech #investing #ai #machinelearning', 'SPAM', NOW()),
('Try a multimillionaire traders chatroom and alerts for $49 !', 'SPAM', NOW()),
('Jason Bond wants u to try his trading alerts 4 *FREE* ', 'SPAM', NOW()),
('RT @Escells: $FDBL Friendable Inc.  Nice #SocialMedia App | $NFLX $FB $GOOGL $AAPL $YELP $MEET $MTCH', 'SPAM', NOW()),
('$MKTX $TSLA $FCX $YELP $NVDA $WFC $LOGM #crudeoil #sp500 #nasdaq…', 'SPAM', NOW()),
('Verified $12,880 profit!', 'SPAM', NOW()),
('[Deal Alert] Get a BlackBerry Priv for just $279.99 ($320 off) on #eBay', 'SPAM', NOW()),
('list of free stock picks. #stockpicks #stockmarket', 'SPAM', NOW()),
('This Service Made 20,000% Gains In the Last Month! Subscribe Here', 'SPAM', NOW()),
('@SharePlanner: Allotment of Shares: Don''t Worry About How Many Shares to Buy - #StockMarket #StockTrading', 'SPAM', NOW()),
('@SharePlanner: Allotment of Shares: Don''t Worry About How Many Shares to Buy - #StockMarket #StockTrading', 'SPAM', NOW()),
('@RedDogT3: Tonight''s free recap and look ahead', 'SPAM', NOW()),
('@RisingPennyPlay', 'SPAM', NOW()),
('@SharePlanner: Swing Trading Watchlist for Bullish Trade Setups - SharePlanner', 'SPAM', NOW()),
('Do you know everything while trading in', 'SPAM', NOW()),
('The final edition of this morning''s #stockwatch', 'SPAM', NOW()),
('Bioverativ(BIVV) Proves Attractive To Former Valeant(VRX) Patron ValueAct', 'SPAM', NOW()),
('Expensive Research and Cheap Hedge Funds:', 'SPAM', NOW()),
('received a new alert. Find out why', 'SPAM', NOW()),
('RT @32Trades: Watch List: Tuesday, February 28, 2017 ', 'SPAM', NOW()),
('@hstyliest: day trade $tsla 10min says trim some', 'SPAM', NOW()),
('they can''t see the answers. I can Follow me. We know.', 'SPAM', NOW()),
('#TradersEdge', 'SPAM', NOW()),
('#Trading with #Bitcoin', 'SPAM', NOW()),
('TD customer’s top traded #US #stocks today:', 'SPAM', NOW()),
('Capital+CurrencyRisk', 'SPAM', NOW()),
('@ElixiumCapital #Blockchain #Crypto #Cryptocurrency', 'SPAM', NOW()),
('Recent Option Transactions #optionstrategy #puts #dividend', 'SPAM', NOW()),
('RT @MaglanCapital: $T AT&T Boosts 5G Networks Rollout as Online Video Demand Spikes #SpectrumIsking', 'SPAM', NOW()),
('#HotNewsToday 💡💰 $KBG.V 💡💰 King’s Bay @geniusmedia2 🔥 https://t.co/BYD2jlHI7e 🔥🔥 @kingsbayres', 'SPAM', NOW()),
('RT @drastichs: #Prognosis of #stocks to #fall #significantly #bearish alphabetically', 'SPAM', NOW()),
('RT @BVZ_Investools: #DividendGrowth for the past week courtesy', 'SPAM', NOW()),
('@IliketotweettoU: You Saw He Trolled Me Too?', 'SPAM', NOW()),
('Take action now!, join this awesome community of traders and profit', 'SPAM', NOW()),
('@brianfires: How About These BIG BLOCKS!', 'SPAM', NOW()),
('@IliketotweettoU: After We Already Knew About This!', 'SPAM', NOW()),
('@DowdEdward: This article generated over a 1000 new followers mostly due to spite for Twitter', 'SPAM', NOW()),
('7 lessons from one of the biggest fake traders EVER', 'SPAM', NOW()),
('This guy is really going to make some $$$', 'SPAM', NOW()),
('4 landmark books to guide you on your entrepreneurial journey reading is FUNdamental', 'SPAM', NOW()),
('Earn while you learn with super_trades easy to replicate trading strategy!', 'SPAM', NOW()),
('Take action and make things happen', 'SPAM', NOW()),
('Skim the cream of financial news', 'SPAM', NOW()),
('NEED GUIDANCE WITH STOCK TRADING?? Checkout the Superman of the stock market!', 'SPAM', NOW()),
('Learn how to make huge trading profits! FREE TRIAL!!!', 'SPAM', NOW()),
('The Start of a Bear Market? Pennystocks could be just fine!', 'SPAM', NOW()),
('Millionaire Roadmap, live trading, webinars, conferences + DVDS', 'SPAM', NOW()),
('Investors Underground Free Day Trading Video', 'SPAM', NOW()),
('RT @timothysykes: 4 landmark books to guide you on your entrepreneurial journey reading is FUNdamental $FB $TWTR', 'SPAM', NOW()),
('@ericsaroza: "March Madness Elite Trader" Package is here', 'SPAM', NOW()),
('Student stock traded $15k into $1.1M in just 2 yrs! FREE TRIAL Stock  ALERTS!!!', 'SPAM', NOW()),
('@useintellitrade Want to cash in on the hottest #techstock? $IMTL is poised to pop.', 'SPAM', NOW()),
('Skim the cream of financial news', 'SPAM', NOW()),
('Jason Bond hot stock alerts by clicking link for a [FREE TRIAL]', 'SPAM', NOW()),
('RT @ericsaroza: "March Madness Elite Trader" Package is here', 'SPAM', NOW()),
('https://t.co/qKjFVTs0mP &lt;&lt; Jason Bond hot stock alerts by clicking link for a [FREE TRIAL] $fb $twtr $lnkd', 'SPAM', NOW()),
('https://t.co/kzzDiId5eB &lt;  Read all about how Kevin makes bank with Jason Bond Picks! $NBEV $CARA $TROX $FB $TWTR', 'SPAM', NOW()),
('RT @ericsaroza: "March Madness Elite Trader" Package is here&gt;&gt;&gt;  https://t.co/UwUkGAVdON   $SPY $WTW $FB $NFLX $ATVI $SKLN $DVAX', 'SPAM', NOW()),
('https://t.co/yCsup2RbEP  This newsletter provides resources needed to get started with penny stocks $YMC $CM $NKE $GOOGL', 'SPAM', NOW()),
('RT @OptionAlarm: https://t.co/fgKThJxj1A swing-trade winning since 2006', 'SPAM', NOW()),
('RT @davidmoadel: $SPY The Impossible Stealth Bull Market https://t.co/BaCvapncSM $SPX $DIA $QQQ $IWM $AAPL $GOOG $GOOGL $AMZN $NFLX $FB $TS', 'SPAM', NOW()),
('$SPY The Impossible Stealth Bull Market https://t.co/BaCvapncSM $SPX $DIA $QQQ $IWM $AAPL $GOOG $GOOGL $AMZN $NFLX $FB $TSLA $TWTR', 'SPAM', NOW()),
('$BAC $GOOG $DWTI #pennystocks', 'SPAM', NOW()),
('Get free access to my trading resources library #stocks #trading $AAPL $NFLX $TSLA $GOOGL  https://t.co/ip995RHaSC https://t.co/iaMYcTM1Gg', 'SPAM', NOW()),
('RT @InvestorHangout: We are LIVE Covering:', 'SPAM', NOW()),
('Are you Bullish or Bearish on #Snapchat? Start #Trading $SNAP with #Bitcoin. 15:1 Leverage. #Stocks #Fintech #BTC… https://t.co/mAnr3lus67', 'SPAM', NOW()),
('Trade with the best indicators', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW()),
('', 'SPAM', NOW());

,
('', 'SPAM', NOW())

INSERT INTO training_data (text, label, created_at) VALUES
('Not much of a hero call, but I''m doing it anyways. The bottom is in for $TWTR', 'NON-SPAM', NOW()),
('Apple expected to reveal new 10.5-inch iPad Pro at WWDC #AppleInsider $AAPL', 'NON-SPAM', NOW()),
('Steve Ballmer wants to Donate most his fortune to save the birds @Twitter $TWTR', 'NON-SPAM', NOW()),
('$NVDA "Re: Google''s TPU" on The Motley Fool message boards:', 'NON-SPAM', NOW()),
('NVIDIA''s Explosive Growth in 5 Charts @themotleyfool #stocks $NVDA', 'NON-SPAM', NOW()),
('NVIDIA is at the center of a perfect storm of opportunities in gaming, AI, and self-driving platforms', 'NON-SPAM', NOW()),
('Where Does #Nvidia Go From Here? - $nvda #tech #stocks #investing #ai #machinelearning #iot #gaming #deeplearning', 'NON-SPAM', NOW()),
('#Nvidia: Not A Convincing ''Buy The Dip'' Situation - $nvda #tech #ai #investing #machinelearning', 'NON-SPAM', NOW()),
('$ACN Accenture Brings to Life the Accenture Innovation Architecture at Mobile World Congress to Help Orga', 'NON-SPAM', NOW()),
('Technical Stock Chart Resistance Level Approaching On Accenture $ACN #VerifiedProTrader', 'NON-SPAM', NOW()),
('#EquityResearch Buffett Should Be Buying Accenture $ACN', 'NON-SPAM', NOW()),
('$YELP nice recovery with strong call action Friday', 'NON-SPAM', NOW()),
('T @marketminute: $YELP pointed out Fri-now moving up nicely', 'NON-SPAM', NOW()),
('Michael Stoppelman Sells 7,784 Shares of Yelp Inc. $YELP Stock', 'NON-SPAM', NOW()),
('Daily Reversal (09:46): $YELP Last: 33.93; pHigh: 33.74; rVol: 0.512; pClose: 33.46; LOD: 33.6000; Perf: 1.4%', 'NON-SPAM', NOW()),
('SVP of eBay Inc. just disposed of 13,400 shares', 'NON-SPAM', NOW()),
('#eBay Ebay partners with new social app Snupps. Read more:', 'NON-SPAM', NOW()),
('$EBAY nice close today..will start watching this one closely', 'NON-SPAM', NOW()),
('$EBAY (EBAY) stock confirmed continuation breakout on a bull flag', 'NON-SPAM', NOW()),
('eBay Inc $EBAY SVP Stephen Fisher Sells 16,601 Shares of Stock', 'NON-SPAM', NOW()),
('#Amazon''s Success With ''Manchester'' Points to Changes in Movie Business. Read more:', 'NON-SPAM', NOW()),
('Home Assistants like #Amazon Echo Could Be a Boon for Assisted Living. Read more:', 'NON-SPAM', NOW()),
('RT @arjunsethi: For those confused about why $AMZN cares about the gaming space.', 'NON-SPAM', NOW()),
('Amazon Stock: Best Current Wealth-Building Choice, As Now Seen By Big-$ Funds', 'NON-SPAM', NOW()),
('#Amazon is teaching Alexa to distinguish different voices. Read more:', 'NON-SPAM', NOW()),
('#Amazon To Sell Beer and Wine at Its New Hi-Tech Convenience Store. Read more', 'NON-SPAM', NOW()),
('RT @craigbuj: tipping point for Alibaba Cloud', 'NON-SPAM', NOW()),
('#Amazon To Sell Game Downloads From Twitch Streams', 'NON-SPAM', NOW()),
('#GoldmanSachs announces India Impact Fund winners.', 'NON-SPAM', NOW()),
('@GoldmanSachs: A look at 3 of the most promising innovations in materials science, with $GS Research:', 'NON-SPAM', NOW()),
('Why $GS Research’s Jeff Currie sees rising demand for oil', 'NON-SPAM', NOW()),
('Lotta guys said $gs was going to rocket yesterday', 'NON-SPAM', NOW()),
('209,462 Shares in Microsoft Corporation $MSFT Acquired by Ffcm LLC', 'NON-SPAM', NOW()),
('#Microsoft''s Android Launcher 3.0 Publicly Released, 3.1 Version Already in Beta. Read more:', 'NON-SPAM', NOW()),
('#Microsoft, Others To Announce Blockchain Alliance. Read more: ', 'NON-SPAM', NOW()),
('#Microsoft opens Data Insights Summit 2017 registration.', 'NON-SPAM', NOW()),
('$TAPM and a few mobile gaming stocks to keep an eye on. This industry is experiencing incredible growth', 'NON-SPAM', NOW()),
('@firstadopter: Microsoft to launch a games subscription service $MSFT', 'NON-SPAM', NOW()),
('The technical reason why Tesla shares could soon rise 54% $TSLA @teslamotors @elonmusk #model3', 'NON-SPAM', NOW()),
('Here''s What The Media Is Ignoring About $TSLA Sketchy Earnings', 'NON-SPAM', NOW()),
('@aznboi27: Love $TSLA does not matter what market does, has a mind of it''s own', 'NON-SPAM', NOW()),
('Surprise this nugget of reality on $tsla isn''t coming from @markbspiegel', 'NON-SPAM', NOW()),
('@HughJRobbins: $TSLA was already 60 over their price target. The new price target is only $5 less than the old one. #stocks #investing', 'NON-SPAM', NOW()),
('Why Moats Matter: The Morningstar Approach to Stock Investing:', 'NON-SPAM', NOW()),
('@FoxBusiness: #StockAlert - Stocks to watch today on #WallStreet', 'NON-SPAM', NOW()),
('This is a GREAT $TSLA article. Only flaw is he''s low on the sharecount as earnings PR used average of pre', 'NON-SPAM', NOW()),
('Intel EVP Diane M. Bryant Sells $2,028,535.14 in $INTC via @RatingsNetwork', 'NON-SPAM', NOW()),
('The Hype Surrounding Advanced Micro Device''s Ryzen Product Launch $AMD $INTC  via @benzinga', 'NON-SPAM', NOW()),
('$AMD Superior Performance APUs will cause $AAPL to Switch to AMD from $INTC', 'NON-SPAM', NOW()),
('Today in Apple history: Mac mini arrives with #Intel inside. Read more:', 'NON-SPAM', NOW()),
('Benzinga: Jim Cramer Weighs In On Digital Realty Trust, Intel, ServiceNow And Xerox', 'NON-SPAM', NOW()),
('Top 10 Technology Stocks For Growth And Income', 'NON-SPAM', NOW()),
('@amigobulls: Advanced Micro Devices, Inc. (AMD) Stock Will Head Higher Going Into Vega Preview', 'NON-SPAM', NOW()),
('#Intel Security breaks down the vulnerabilities of a ''Smart Future''', 'NON-SPAM', NOW()),
('@SamanthaLaDuc: I covered $UPS short (regretably!) but still holding short', 'NON-SPAM', NOW()),
('Commented on AMD: Ryzen Rockets Off In Stages', 'NON-SPAM', NOW()),
('RT @InvestorPlace: AMD Stock Still Has at Least 15% Upside on New Chips $AMD $INTC', 'NON-SPAM', NOW()),
('$NVDA analysis @ Morning Call Express: Election Explosion Rally:', 'NON-SPAM', NOW()),
('Supply constraints will limit OLED to just ''iPhone 8,'' benefitting #Apple in long run - rep... ', 'NON-SPAM', NOW()),
('Finance geeks give $INTC 17 BUY and 3 SELL votes. Enter here if you''d buy or sell $INTC:', 'NON-SPAM', NOW()),
('RT @Echofox82: Larry Summers is worried about enormous damage to the economy', 'NON-SPAM', NOW()),
('$AAPL the higher it goes before a significant dip, the less likely you are to see $130 on that significant dip.', 'NON-SPAM', NOW()),
('Apple Inc  Reiterated Rating by Guggenheim Securities (Ranked 9th) to Buy with', 'NON-SPAM', NOW()),
('RT @siliconbeat: Buffett''s Berkshire boosts buys of Apple, now owns 133 million shares', 'NON-SPAM', NOW()),
('What is it ahead for US Tech Giants? Check what analysts have to say', 'NON-SPAM', NOW()),
('If $SNAP is a camera company, does that make its largest competitor $AAPL?', 'NON-SPAM', NOW()),
('Guggenheim elevates Apple target to $180', 'NON-SPAM', NOW()),
('Warren Buffett doubled holdings of $AAPL in Jan., Berkshire now owns 133M shares of Apple, a 2.5% stake,worth $17B', 'NON-SPAM', NOW()),
('#Apple is turning the iPhone into a Samsung Galaxy phone. Read more:', 'NON-SPAM', NOW()),
('AT&T Wireless Remains In Trouble, And The Stock May Suffer Soon:', 'NON-SPAM', NOW()),
('RT @MaglanCapital: $T AT&T Boosts 5G Networks Rollout as Online Video Demand Spikes #SpectrumIsking', 'NON-SPAM', NOW()),
('RT @amalist: And for the next 90 years which 14 stocks must we own:', 'NON-SPAM', NOW()),
('#ATT A&amp;, T-Mobile Trade Punches In Mobile War . Read more', 'NON-SPAM', NOW()),
('#ATT LAA is on #AT''s Roadmap but It''s More Worried About Experience than Speed. Read more:', 'NON-SPAM', NOW()),
('#ATT Wireless carriers are quietly influencing what videos you watch on your phone. Read more:', 'NON-SPAM', NOW()),
('I added $T to my 2017 watchlist last week so I will have to check this out', 'NON-SPAM', NOW()),
('GameStop, Best Buy Hit As Microsoft Prepares Netflix-Style Online Gaming Plan', 'NON-SPAM', NOW()),
('$WMT Target''s $7 billion spending plan still leaves some question marks', 'NON-SPAM', NOW()),
('#Walmart Launches Grocery Price War: Can It Take on Aldi?. Read more:', 'NON-SPAM', NOW()),
('Stocks finish higher for fourth straight month; Dow snaps record run:', 'NON-SPAM', NOW()),
('Target: Between a Rock (Amazon) and a Hard Place (Wal-Mart)', 'NON-SPAM', NOW()),
('Target can''t win using Wal-Mart''s playbook:', 'NON-SPAM', NOW()),
('Warren Buffett warns on Walmart and retail industry $WMT', 'NON-SPAM', NOW()),
('#Walmart Pay tweaked to speed up pharmacy refills, money transfers', 'NON-SPAM', NOW()),
('E-commerce smash and grab ravages retail', 'NON-SPAM', NOW()),
('Target sharpens aim at Amazon, Wal-Mart', 'NON-SPAM', NOW()),
('Is $PYPL breaking out? Take a quick look at #LoveU #DonaldTrump', 'NON-SPAM', NOW()),
('PayPal’s first payments bot is a Slack app', 'NON-SPAM', NOW()),
('SFTW Investor long-term stock recommendation: $PYPL PayPal Holdings, Inc. (SS: 80)', 'NON-SPAM', NOW()),
('Paypal Holdings Inc $PYPL Position Increased by Credit Agricole S A', 'NON-SPAM', NOW()),
('Paypal Holdings Inc $PYPL Lifted to Strong-Buy at Vetr Inc.', 'NON-SPAM', NOW()),
('@BColwell_4IR: #PayPal Agrees To Acquire #TIONetworks For $233 Million - $pypl #fintech #mobilepayments #stocks #investing', 'NON-SPAM', NOW()),
('18 users on Vetr are bullish on PayPal Holdings, Inc., indicating a STRONG BUY Rating (4.5 stars) for $PYPL', 'NON-SPAM', NOW()),
('J. Goldman &amp; Co LP Has $20,513,000 Position in Paypal Holdings Inc $PYPL', 'NON-SPAM', NOW()),
('What is it ahead for US Tech Giants? Check what analysts have to say', 'NON-SPAM', NOW()),
('@AGORACOM: @wtsiolis @Reuters Our poll showed 50% of power users would pay $TWTR $17 / 1,000 followers / year if they had to', 'NON-SPAM', NOW()),
('@coopwatercooler: Big news! $TWTR shareholders to vote @ the 2017 annual meeting on investigating an #EquitableExit to a user-owned', 'NON-SPAM', NOW()),
('@jack @anthonynoto If you charge for #Twitter, #RIPTwitter.  $TWTR', 'NON-SPAM', NOW()),
('#Twitter may offer a subscription version of its service to brands and news outlets... via @launchticker', 'NON-SPAM', NOW()),
('RT @Stonefoxcapital: $TWTR starting to look a lot like #LinkedIn that $MSFT bought for $26B', 'NON-SPAM', NOW()),
('@CaseyNewton $TWTR #Moments Total waste of resources.', 'NON-SPAM', NOW()),
('@twitter and @facebook get unlimited data in Mexico wireless plan', 'NON-SPAM', NOW()),
('RT @YTAcct: @ocdstockjockey What ever will $twtr investors do. 🤔Twitter.', 'NON-SPAM', NOW()),
('RT @MUJosey: @preach I''m curious what affect that would have on $Twtr lol', 'NON-SPAM', NOW()),
('Netflix Is Ready for Its Next Disruptive Move @themotleyfool #stocks $NFLX', 'NON-SPAM', NOW()),
('Where Will Netflix, Inc. Be in 10 Years? $NFLX #netflix #investing #stockmarket #streaming #TV #business', 'NON-SPAM', NOW()),
('$NFLX fell off the channel and got resisted at 35MA daily. gap down is on the way. #bearish #short', 'NON-SPAM', NOW()),
('RT @Seventeen_Mile: Netflix: The Monster That’s Eating Hollywood', 'NON-SPAM', NOW()),
('RT @WallStJesus: ⤵TOP DROPS IN NASDAQ SHORTS:', 'NON-SPAM', NOW()),
('$NFLX Stock appeared as if it was ready to break out this week, but pulled back as the market''s jitters impacted', 'NON-SPAM', NOW()),
('$NFLX $AMT $FB: 3 Tech Stocks That Belong in Any Portfolio:', 'NON-SPAM', NOW()),
('$NFLX Max Pain is 143.00 for maturity 03/31/2017. Prev Close = 142.02.', 'NON-SPAM', NOW()),
('$FB high open interest range is 133.00 to 142.00 for option expiration 03/31/2017', 'NON-SPAM', NOW()),
('$FB can''t get organic engagement and continues to destroy their user experience in exchange for "engagement"', 'NON-SPAM', NOW()),
('Facebook, Inc. Steps Up Its Live Video Tech @themotleyfool', 'NON-SPAM', NOW()),
('$FB is topping here.', 'NON-SPAM', NOW()),
('$FB Shares traded flat this week and from a relative strength standpoint, the action has been quite consistent in', 'NON-SPAM', NOW()),
('War of the Worlds Episode 5: Apple''s iPhone-inspired toilets, #Intel vs. AMD, and more. Read more:', 'NON-SPAM', NOW()),
('RT @NaviAvatar1: Trumpcare pulled from Vote. Stocks bounce $AAPL $FB $BABA https://t.co/j53vLscH8q', 'NON-SPAM', NOW()),
('$FB fell of the channel and bounced back. watching now. I don’t get a clear message. but 30m 250MA worth watching. https://t.co/KI4hz8J40N', 'NON-SPAM', NOW()),
('$FB high open interest range is 133.00 to 142.00 for option expiration 03/31/2017. https://t.co/u0mmxS4M4m https://t.co/2bhwWhRODg', 'NON-SPAM', NOW()),
('$FB CEO Mark Zuckerberg sold 375332 shares in trans dated March 20th. Sold at avg price of $139.87, for total of $52497686.84', 'NON-SPAM', NOW()),
('$FB Shares traded flat this week and from a relative strength standpoint, the action has been quite consistent in … https://t.co/5cVPFfEjCQ', 'NON-SPAM', NOW()),
('.@Nike sees record sales thru its #MobileApp, says #Digital shoppers spend 2x more than brick &amp; mortar #retail $NKE', 'NON-SPAM', NOW()),
('Nike, Inc.: Premiums and Discounts #dividend #optionstrategy #justdoit $NKE', 'NON-SPAM', NOW()),
('#Nike Has Dropped Clues That It Could Shock Wall Street. Read more: https://t.co/dpOFTQzBNC $NKE', 'NON-SPAM', NOW()),
('#Nike''s biggest-ever price drop can be blamed for Dow''s fifth-straight loss. Read more: https://t.co/DY4pthRziL $NKE', 'NON-SPAM', NOW()),
('YahooFinance: Nike CEO: ''Digital is the foundation'' of retail now readDanwrite $NKE https://t.co/6u8kt2VtPF https://t.co/leywSFc0k4 #BSAF', 'NON-SPAM', NOW()),
('RT @MorningstarInc: 2 Reasons We''re Optimistic About Nike https://t.co/ARSAR0onMN $NKE https://t.co/MYX4aP9Rrh', 'NON-SPAM', NOW()),
('Adidas Mark King Talks About The Companys Comeback, Turning The Corner In North America $ADDYY $NKE $UAA https://t.co/Lvp4i0ifUm @benzinga', 'NON-SPAM', NOW()),
('In honor of the #Ducks playing tonight, the largest public company in Oregon is $NKE , headquarters in Beaverton. Good luck #oregonducks', 'NON-SPAM', NOW()),
('Bounce up off #200DMA, smashed through #50DMA. Price is #doingWork $NKE https://t.co/G2n1lkHQ0r', 'NON-SPAM', NOW()),
('Here''s Why #Nike''s Stock Is Falling Despite a Slam Dunk Quarter. Read more: https://t.co/6nS835Dy4Q $NKE', 'NON-SPAM', NOW()),
('RT @tasciccac: $DJIA WKLY Best performing $MCD $AAPL $DIS $CVX $KO $MSFT $INTC $WMT $CSCO Worst $GS $JPM $UNH $NKE $BA $DD $JNJ', 'NON-SPAM', NOW()),
('How To Advertise On Google And Get Great Results - Huffington Post https://t.co/mPAfmh4kgs #Google $GOOG $GOOGL https://t.co/HrEbB8zuU1', 'NON-SPAM', NOW()),
('RT SeekingAlpha: https://t.co/U1r1iPbcW2 Daily Round Up 7/1/16: AXDX, OPK, IMH, SCYX https://t.co/aVF943G1rw $ADBE $CLGX $EXR $GOOG $IMH', 'NON-SPAM', NOW()),
('Frontier Lines Up Against Google Fiber in AT&amp;T Fight Over Utility Pole Access https://t.co/HOeUy8nK1t $GOOG', 'NON-SPAM', NOW()),
('Scrutiny of Google #Tax liabilities intensifies with Spanish raid $GOOG #Technology #Share #GlobalNews https://t.co/2HZyKeKcHV', 'NON-SPAM', NOW()),
('RT @mdudas: The duopoly that rules online ads, $FB + $GOOG, is eliminating distinctions btw 1st &amp; 3rd party data ~ @profcarroll', 'NON-SPAM', NOW()),
('RT @racernic: $AAPL vs. $GOOGl $AMZN today''s action. if you chased aapl down on open u lost money. here is what hapnd https://t.co/21jIk3NG', 'NON-SPAM', NOW()),
('Alphabet’s $GOOG “Underperform” Rating Reiterated at Wedbush https://t.co/teAjzFznhA', 'NON-SPAM', NOW()),
('Alphabet Inc $GOOG Given Underperform Rating at Wedbush https://t.co/fkXyi21ql5', 'NON-SPAM', NOW()),
('$GOOG received a new alert. Find out why at https://t.co/nZwqReM0tj #stocks #daytrading #trading #mkt  #NYSE #NASDAQ #markets 161', 'NON-SPAM', NOW()),
('#Nvidia is a lot bigger than #selfdrivingcars #MedicalImages #mri #xray #Google #ibm $GOOGL $GOOG $IBM $NVDA #CANCER https://t.co/NIVP4Wti1D', 'NON-SPAM', NOW()),
('$GOOG Google&amp;apos;s head of Pixel smartphone division leaves after six months https://t.co/o4MCCFTAIB', 'NON-SPAM', NOW()),
('RT @mcwm: Google is up big on another kickass earnings report', 'NON-SPAM', NOW()),
('These are the companies investing most aggressively in #AR and #VR https://t.co/Wfa7lDEAZ5 $INTC $QCOM $FB $GOOGL $CMCSA', 'NON-SPAM', NOW()),
('Snapchat may need to switch to an algorithmic feed to increase user growth... via @JoshConstine | $SNAP $FB #Tech https://t.co/hTrdDvk9CG', 'NON-SPAM', NOW()),
('Will be taking some of my $twtr gains over to $snap calls end of the week.  I see snap going much higher.', 'NON-SPAM', NOW()),
('Twitter''s First Quarter Was Good. Instagram''s Was Better. @themotleyfool #stocks $FB, $TWTR, $SNAP https://t.co/ere1E2x9AT', 'NON-SPAM', NOW()),
('Yo follow the StockTwits Snapchat right now it''s just getting started. Tha takeover $SNAP', 'NON-SPAM', NOW()),
('If You Think Netflix, Amazon Disrupted Hollywood, You''ll Love $Snap https://t.co/LN6QgkRWb1', 'NON-SPAM', NOW()),
('When 2 personalities with the same fire and passion meet, they create $GOOG $SNAP ....; create #BetterLiving', 'NON-SPAM', NOW()),
('$SNAP people still buying the hype when they shouldn''t  https://t.co/J9O4we5wBJ  $FB', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW()),
('', 'NON-SPAM', NOW());

,
('', 'NON-SPAM', NOW())


 --T      | AT&T, Inc.                    | 2016-05-30 | t
 --WMT    | Wal-Mart Stores Inc.          | 2016-05-30 | t
 --PYPL   | PayPal Holdings, Inc.         | 2016-05-30 | t
 --TWTR   | Twitter, Inc.                 | 2016-05-30 | t
 --NFLX   | Netflix, Inc.                 | 2016-05-30 | t
 --FB     | Facebook Inc.                 | 2016-05-30 | t
 --NKE    | Nike, Inc.                    | 2016-05-30 | t
 --GOOG   | Alphabet Inc.                 | 2016-05-30 | t
 SNAP   | Snap Inc.                     | 2017-02-27 | t
 F      | Ford Motor Company            | 2017-02-27 | t
 V      | Visa Inc.                     | 2017-02-27 | t
 AMD    | Advanced Micro Devices, Inc.  | 2017-02-27 | t
 BIDU   | Baidu, Inc.                   | 2017-02-27 | t
 MON    | Monsanto Company              | 2017-02-27 | t
 S      | Sprint Corporation            | 2017-03-01 | t
 M      | Macy's Inc                    | 2017-03-01 | t
 C      | Citigroup, Inc.               | 2017-03-01 | t
 JPM    | JP Morgan Chase & Co.         | 2017-03-01 | t
 GM     | General Motors Company        | 2017-03-01 | t
 HPQ    | HP Inc.                       | 2017-03-01 | t
 PG     | Procter & Gamble Company      | 2017-03-01 | t
 SQ     | Square, Inc.                  | 2017-03-01 | t
 CSCO   | Cisco Systems, Inc.           | 2017-03-01 | t
 ZNGA   | Zynga Inc.                    | 2017-03-01 | t
 FIT    | Fitbit, Inc.                  | 2017-03-01 | t
 BABA   | Alibaba Group Holding Limited | 2017-03-01 | t
 ORCL   | Oracle Corporation            | 2017-03-23 | t
 UA     | Under Armour, Inc.            | 2017-03-23 | t
 GE     | General Electric Company      | 2017-03-23 | t
 DIS    | Walt Disney Company           | 2017-03-23 | t
 VZ     | Verizon Communications Inc.   | 2017-03-23 | t
 BA     | Boeing Company                | 2017-03-23 | t
 GPRO   | GoPro, Inc.                   | 2017-03-23 | t
 CRM    | Salesforce.com Inc            | 2017-03-23 | t
 LNKD   | LinkedIn Corporation          | 2016-05-30 | f
 SCTY   | SolarCity Corporation         | 2016-05-30 | f
 KO     | Coca-Cola Company             | 2017-04-03 | f
