/**
 * @file Defines socket event constants.
 * @author Simon Lindgren, <simon.g.lindgren@gmail.com>
 */

'use strict';

module.exports = {
  CONNECTION: 'connection',
  NEW_TWITTER_DATA: "NEW_TWITTER_DATA",
  GET_CLIENT_INFO: "GET_CLIENT_INFO",
  DISPATCH_CLIENT_INFO: "DISPATCH_CLIENT_INFO",
  FETCH_SEARCH_RESULTS: "FETCH_SEARCH_RESULTS",
  DISPATCH_SEARCH_RESULTS: "DISPATCH_SEARCH_RESULTS",
  FETCH_TWITTER_DATA: "FETCH_TWITTER_DATA",
  DISPATCH_TWITTER_DATA: "DISPATCH_TWITTER_DATA",
  TWITTER_DATA_FAILURE: "TWITTER_DATA_FAILURE",
  UPDATE_STOCKLIST: "UPDATE_STOCKLIST",
  FETCH_NEWS_ITEMS: "FETCH_NEWS_ITEMS",
  DISPATCH_NEWS_ITEMS: "DISPATCH_NEWS_ITEMS"
}
