apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-server
  namespace: mimir
  labels:
    app: app-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
        - name: app-server
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/app-server:latest
          ports:
            - name: app-server-port
              containerPort: 3000
          env:
            - name: DB_HOST
              value: app-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: password
