apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: news-ranker
  namespace: mimir
  labels:
    app: news-ranker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news-ranker
    spec:
      containers:
        - name: news-ranker
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/news-ranker:latest
          ports:
            - name: nr-port
              containerPort: 5000
          env:
            - name: PG_HOST
              value: news-db
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: news-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: news-db-credentials
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: news-db-credentials
                  key: database
            - name: cluster_host
              value: news-clusterer
            - name: cluster_port
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: news-clusterer
