apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: price-server
  namespace: mimir
  labels:
    app: price-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: price-server
    spec:
      containers:
        - name: price-server
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/price-server:latest
          ports:
            - name: ps-port
              containerPort: 4000
          env:
            - name: PG_HOST
              value: price-db
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: price-db-credentials
                  key: password
