apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spam-filter
  namespace: mimir
  labels:
    app: spam-filter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spam-filter
    spec:
      containers:
        - name: spam-filter
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/spam-filter:latest
          ports:
            - name: sf-port
              containerPort: 1000
          env:
            - name: PG_HOST
              value: tweet-db
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: database
