apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: volume-counter
  namespace: mimir
  labels:
    app: volume-counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: volume-counter
    spec:
      containers:
        - name: volume-counter
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/volume-counter:latest
          env:
            - name: PG_HOST
              value: tweet-db
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tweet-db-credentials
                  key: database
            - name: STABLE_DATE
              value: "2017-09-01"
            - name: server_ip
              value: app-server
            - name: server_port
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: app-server
