apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mimir-proxy
spec:
  rules:
    - host: dev.mimir.news
      http:
        paths:
          - path: /api/app/
            backend:
              serviceName: app-server
              servicePort: 3000
          - path: /api/price/
            backend:
              serviceName: price-server
              servicePort: 4000
          - path: /api/news/
            backend:
              serviceName: news-server
              servicePort: 5050
          - path: /api/search/
            backend:
              serviceName: search-server
              servicePort: 7000
          - path: /api/search
            backend:
              serviceName: search-server
              servicePort: 7000
          - backend:
              serviceName: webserver
              servicePort: 8080
    - host: db.dev.mimir.news
      http:
        paths:
          - backend: mimir-dbui
            servicePort: 8081
