/* ---- User actions ---- */
export const LOG_IN = "LOG_IN";
export const RECIVE_USER_CREDENTIALS = "RECIVE_USER_CREDENTIALS";
export const LOG_OUT = "LOG_OUT";

/* ---- Tickers actions ---- */
export const FETCH_UNTRACKED_TICKERS = "FETCH_UNTRACKED_TICKERS";
export const RECIVE_UNTRACKED_TICKERS = "RECIVE_UNTRACKED_TICKERS";
export const START_TRACKING_TICKER = "START_TRACKING_TICKER";
export const RECIVE_TICKER_DESCRIPTION = "RECIVE_TICKER_DESCRIPTION";

/* ---- Stocks actions ---- */
export const FETCH_TRACKED_STOCKS = "FETCH_TRACKED_STOCKS";
export const RECIVE_TRACKED_STOCKS = "RECIVE_TRACKED_STOCKS";
export const SAVE_STOCK_INFO = "SAVE_STOCK_INFO";
