apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-db-vol-claim
  namespace: mimir
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Mi
