apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: news-clusterer
  namespace: mimir
  labels:
    app: news-clusterer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news-clusterer
    spec:
      containers:
        - name: news-clusterer
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/news-clusterer:latest
          ports:
            - name: nc-port
              containerPort: 6000
          env:
            - name: DB_HOST
              value: news-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: news-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: news-db-credentials
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: news-db-credentials
                  key: database
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: news-db
            - name: NEWS_CLUSTERER_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: news-clusterer
          livenessProbe:
            httpGet:
              path: /health
              port: nc-port
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: nc-port
            initialDelaySeconds: 30
