apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: total-volume-counter
  namespace: mimir
  labels:
    app: total-volume-counter
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: close-price-retriver
              image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/total-volume-counter:latest
              env:
                - name: DB_HOST
                  value: tweet-db
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: tweet-db-credentials
                      key: password
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: tweet-db-credentials
                      key: username
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: tweet-db-credentials
                      key: database
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: service-ports
                      key: tweet-db
                
