apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: price-server
  namespace: mimir
  labels:
    app: price-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: price-server
    spec:
      containers:
        - name: price-server
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/price-server:latest
          ports:
            - name: ps-port
              containerPort: 4000
          env:
            - name: DB_HOST
              value: price-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: price-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: price-db-credentials
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: price-db-credentials
                  key: database
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: price-db
            - name: PRICE_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: price-server
          livenessProbe:
            httpGet:
              path: /health
              port: ps-port
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: ps-port
            initialDelaySeconds: 30
