apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-listener
  namespace: mimir
  labels:
    app: stream-listener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stream-listener
    spec:
      containers:
        - name: stream-listener
          image: 377827096411.dkr.ecr.eu-central-1.amazonaws.com/mimir/stream-listener:1.0-java
          env:
            - name: TWEET_HANDLER_HOST
              value: tweet-handler
            - name: TWEET_HANDLER_PROTOCOL
              value: http
            - name: TWEET_HANDLER_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: tweet-handler
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: twitter-api-credentials
                  key: consumerKey
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-api-credentials
                  key: consumerSecret
            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twitter-api-credentials
                  key: accessToken
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-api-credentials
                  key: accessSecret
            - name: HEARTBEAT_FILE
              value: /tmp/STREAM_LISTENER_HEARTBEAT.txt
            - name: HEARTBEAT_INTERVAL
              value: "15"
          readinessProbe:
            exec:
              command:
                - test
                - '`find /tmp/STREAM_LISTENER_HEARTBEAT.txt -mmin 1`'
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            exec:
              command:
                - test
                - '`find /tmp/STREAM_LISTENER_HEARTBEAT.txt -mmin 1`'
            initialDelaySeconds: 15
            periodSeconds: 15
