CREATE TABLE ARTICLE (
  URL_HASH VARCHAR(64) PRIMARY KEY,
  URL VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  REFERENCE_SCORE NUMERIC(6,5) NOT NULL,
  SUMMARY TEXT,
  BODY TEXT,
  TIMESTAMP TIMESTAMP,
  TWITTER_REFERENCES BIGINT[],
  KEYWORDS VARCHAR(50)[]
);

CREATE TABLE COMPOUND_SCORE (
  URL_HASH VARCHAR(64) REFERENCES ARTICLES(URL_HASH),
  TICKER VARCHAR(15),
  SCORE NUMERIC(6,5) NOT NULL,
  PRIMARY KEY (URL_HASH, TICKER)
);

CREATE TABLE SUBJECT_SCORE (
  URL_HASH VARCHAR(64) REFERENCES ARTICLES(URL_HASH),
  TICKER VARCHAR(15),
  SCORE NUMERIC(6,5),
  PRIMARY KEY (URL_HASH, TICKER)
);

CREATE TABLE ARTICLE_CLUSTER (
  TITLE VARCHAR(255),
  TICKER VARCHAR(15),
  LEADER
  SCORE 
)

CREATE TABLE CLUSTER_MEMBER (
  URL_HASH VARCHAR(64) PRIMARY KEY,
  REFERENCE_SCORE NUMERIC(6,5) NOT NULL,
  SUBJECT_SCORE NUMERIC(6,5) NOT NULL,
);
