apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-db-vol-claim
  namespace: mimir
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs-standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
